name: blood_donation_app
description: "A desktop application for managing blood donors and requests for the LifeBlood App."
publish_to: 'none'  # Prevents accidential publishing to pub.dev

# App version
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ^3.7.2

# -----------------------------------------------------------------------
# Dependencies: Core Flutter and Third-party Packages
# -----------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter  # Core Flutter SDK

  # Cupertino icons (used for iOS-style icons/widgets)
  cupertino_icons: ^1.0.8
  
  # File picker for selecting any type of file (images, documents, etc.)
  file_picker: ^9.0.2

  # Open files using the default installed application
  open_filex: ^4.7.0

  # Allows saving files to device storage (e.g., downloads)
  file_saver: ^0.2.14

  # Internationalization and date/time formatting
  intl: ^0.20.2

  # Firebase core initialization
  firebase_core: ^3.13.0

  # Firebase authentication support
  firebase_auth: ^5.5.2

  # Firestore database
  cloud_firestore: ^5.6.5

  # Supabase integration (for document/file storage)
  supabase_flutter: ^2.8.4

  # State management
  provider: ^6.1.4

  # Calendar UI
  table_calendar: ^3.2.0
  
  # Set custom window size and constraints (for desktop apps)
  window_size: ^0.1.0

# -----------------------------------------------------------------------
# Development Dependencies: Linting and Testing
# -----------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting rules
  flutter_lints: ^5.0.0

# -----------------------------------------------------------------------
# Flutter Specific Configurations
# -----------------------------------------------------------------------
flutter:
  uses-material-design: true

  # Asset directories
  assets:
    - assets/images/
    - assets/icons/
